spring:
  datasource:
    url: jdbc:mysql://localhost:8889/cloud_vendor?useSSL=false
    username: root
    password: root

#JPA Settings
  jpa.hibernate.ddl_auto: create
  #jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
